spring:
  profiles:
    active: dev, remote
  messages:
    encoding: UTF-8
  output:
    ansi:
      enabled: always
  #  #启动加载图
  banner:
    location: banner.txt
    charset: UTF-8
  servlet:
    multipart:
      max-file-size: 104857600
      max-request-size: 104857600


#  multipart.maxFileSize = 10Mb
#  multipart.maxRequestSize=100Mb
